//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sayHi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sayhi_MangaInfo_CharacterDesign
    {
        public int id { get; set; }
        public Nullable<int> MangaId { get; set; }
        public Nullable<int> CharacterDesignId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> Effect { get; set; }
    }
}
