//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sayHi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sayHi_BookInfo
    {
        public int id { get; set; }
        public int uid { get; set; }
        public string bookName { get; set; }
        public string bookCover { get; set; }
        public string bookState { get; set; }
        public string bookTag { get; set; }
        public string bookType { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool Effect { get; set; }
    }
}
