//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sayHi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sayhi_PlanningInfo_ParticipateIn
    {
        public int id { get; set; }
        public int PlanningId { get; set; }
        public int ParticipantId { get; set; }
        public int CharacterDesignId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool Effect { get; set; }
    }
}
